# structure
NUM_TOKENS = 32
EMBEDDING_SIZE = 512
POSITIONAL_ENCODING_SCALAR = 10_000
POSITIONAL_ENCODING_COEFFICIENTS = 300
NUM_HEADS = 8
NUM_ENCODERS = 6

# train
BATCH_SIZE = 3
TRAIN_NUM_EPOCHS = 1
